### ISSUE TITLE
Tracing using TF returns too late sometimes

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#2877]
**Describe the bug**
Tracing instructions using the lDOS debugger sometimes executes too much, returning control flow to the debugger terminal later than expected. This seems to happen reproducibly on some specific instructions.

**To Reproduce**
Boot lDOS kernel with HMA use. Run `ldebug /t`, then `tsr`, then `g FFFE:09B0`. Then trace the following instructions using `t`.

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20260520-4680-g849a11e06
C:\>ldebug /t
-tsr
Patched PSP at 00B1, now resident.
-g FFFE:09B0
AX=0000 BX=0000 CX=0000 DX=0000 SP=FFF6 BP=0000 SI=0000 DI=0000
DS=00B1 ES=00B1 SS=00B1 CS=FFFE IP=09B0 NV UP DI NG NZ AC PE CY
FFFE:09B0 E85410            call    1A07
-t
AX=0000 BX=0000 CX=0000 DX=0000 SP=FFF4 BP=0000 SI=0000 DI=0000
DS=00B1 ES=00B1 SS=00B1 CS=FFFE IP=1A07 NV UP DI NG NZ AC PE CY
FFFE:1A07 1E                push    ds
-
AX=0000 BX=0000 CX=0000 DX=0000 SP=FFF8 BP=0000 SI=0000 DI=0000
DS=B116 ES=00B1 SS=00B1 CS=FFFE IP=09BE NV UP DI NG NZ AC PO CY
FFFE:09BE 74A1              jz      0961                            not jumping
-
```

The `push ds` at 1A07h should be traced with TF and the next register dump is expected to contain `IP=1A08`

**Attach program/game binaries or provide an URL**
https://pushbx.org/ecm/test/20260520.2/

**Attach the log**
https://pushbx.org/ecm/test/20260520.2/boot.log

**A regression?**
Yes, 59b19ff26b77994760ec7d9745b15c48cf08be11 worked.

**dosemu2 origins**
git

**Additional info**
No KVM, running lDOS kernel, FreeCOM, lDebug.

**Comment by ecm-pushbx** [comment]
Cannot reproduce in a debuggee with PSP = CS = 29ADh on FreeDOS kernel. Might be specific to lDOS kernel or running in the HMA.

**Comment by stsp** [comment]
Try $_cpuemu=(1) for SIM mode.

**Comment by ecm-pushbx** [comment]
Context of that code:

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20260520-4680-g849a11e06
C:\>ldebug /t
-tsr
Patched PSP at 00B1, now resident.
-g FFFE:09B0
AX=0000 BX=0000 CX=0000 DX=0000 SP=FFF6 BP=0000 SI=0000 DI=0000
DS=00B1 ES=00B1 SS=00B1 CS=FFFE IP=09B0 NV UP DI NG NZ AC PE CY
FFFE:09B0 E85410            call    1A07
-u
FFFE:09B0 E85410            call    1A07
FFFE:09B3 8ED8              mov     ds, ax
FFFE:09B5 58                pop     ax
FFFE:09B6 80FC51            cmp     ah, 51
FFFE:09B9 74A6              jz      0961
FFFE:09BB 80FC62            cmp     ah, 62
FFFE:09BE 74A1              jz      0961
FFFE:09C0 80FC50            cmp     ah, 50
FFFE:09C3 7496              jz      095B
FFFE:09C5 80FC33            cmp     ah, 33
FFFE:09C8 7503              jnz     09CD
FFFE:09CA E939FF            jmp     0906
FFFE:09CD 80FC64            cmp     ah, 64
-t
AX=0000 BX=0000 CX=0000 DX=0000 SP=FFF4 BP=0000 SI=0000 DI=0000
DS=00B1 ES=00B1 SS=00B1 CS=FFFE IP=1A07 NV UP DI NG NZ AC PE CY
FFFE:1A07 1E                push    ds
-
AX=0000 BX=0000 CX=0000 DX=0000 SP=FFF8 BP=0000 SI=0000 DI=0000
DS=B116 ES=00B1 SS=00B1 CS=FFFE IP=09BE NV UP DI NG NZ AC PO CY
FFFE:09BE 74A1              jz      0961                            not jumping
-
AX=0000 BX=0000 CX=0000 DX=0000 SP=FFF8 BP=0000 SI=0000 DI=0000
DS=B116 ES=00B1 SS=00B1 CS=FFFE IP=09C0 NV UP DI NG NZ AC PO CY
FFFE:09C0 80FC50            cmp     ah, 50
-u 1A07
FFFE:1A07 1E                push    ds
FFFE:1A08 B80000            mov     ax, 0000
FFFE:1A0B 8ED8              mov     ds, ax
FFFE:1A0D A1C600            mov     ax, [00C6]
FFFE:1A10 1F                pop     ds
FFFE:1A11 C3                retn
FFFE:1A12 1E                push    ds
FFFE:1A13 56                push    si
FFFE:1A14 E8C83F            call    59DF
FFFE:1A17 7547              jnz     1A60
FFFE:1A19 36803EA00A00      cmp     byte [ss:0AA0], 00
FFFE:1A1F 7505              jnz     1A26
FFFE:1A21 B405              mov     ah, 05
FFFE:1A23 E84D33            call    4D73
FFFE:1A26 B484              mov     ah, 84
-
```

**Comment by ecm-pushbx** [comment]
Same results.

**Comment by ecm-pushbx** [comment]
I'm using this command to run: `; ~/local.new/bin/dosemu -I "serial { com 2 device /tmp/vptty-dos }"  -I "floppy { device diskempt.img }" -dumb -td -kt -D+9d+9x+9D -I "ems { 14000 }" -I "disk { hdimage small32.img }" -I "serial { com 1 exec \\\"cat output.txt\\\" }"; stty sane; /sbin/dosfsck -n diskempt.img`

**Comment by ecm-pushbx** [comment]
This is the dosemu rc file:

```
$ cat ~/.dosemurc
$_lredir_paths = "/home/[user]"
$_unix_exec = "/home/[user]/bin/hg"
# $_set_int_hooks = (on)
# $_force_int_revect = (on)
$_force_fs_redirect = (off)
$_cpuemu=(1)
```

**Comment by stsp** [comment]
Try dosdebug, it also uses TF.

**Comment by ecm-pushbx** [comment]
The setting a breakpoint seems more complicated but eventually it worked. Traces as intended.

`install indos` in lDebug doesn't help.

**Comment by ecm-pushbx** [comment]
Can you reproduce with the provided files?

**Comment by stsp** [comment]
For what?
dosdebug uses the same TF, and
if the problem is not there - its in
your debugger. If it is there, then
its in simx86 somewhere.

**Comment by ecm-pushbx** [comment]
It's not there in dosdebug but nothing changed in my debugger and it used to work prior to my update.

**Comment by stsp** [comment]
59b19ff is the last commit that
worked, or just commit that worked?

**Comment by ecm-pushbx** [comment]
> [59b19ff](https://github.com/dosemu2/dosemu2/commit/59b19ff26b77994760ec7d9745b15c48cf08be11) is the last commit that worked, or just commit that worked?

Just a commit that worked. Not bisected yet.

I tried recreating the bug using a small test kernel, unfortunately it traces as expected rather than exhibiting the error: https://pushbx.org/ecm/test/20260520.3/testtrac.asm

**Comment by ecm-pushbx** [comment]
Bisecting now

**Comment by ecm-pushbx** [comment]
Keep running into this error:

```
make[2]: *** No rule to make target '/home/[user]/proj/newnewdosemu/bisect/src/base/lib/libbsd/string.h', needed by 'int.o'.  Stop.
```

**Comment by ecm-pushbx** [comment]
touched that file, seems happier now.

**Comment by ecm-pushbx** [comment]
Different revision had these errors eventually:

```
/usr/bin/ld: /home/[username]/proj/newnewdosemu/bisect/src/dosext/builtins/system.c:227: undefined reference to `strlcpy'
/usr/bin/ld: /tmp/libdosemu2.so.0.1.UKlWv9.ltrans12.ltrans.o:/home/[username]/proj/newnewdosemu/bisect/src/dosext/builtins/lredir.c:462: more undefined references to `strlcpy' follow
/usr/bin/ld: /tmp/libdosemu2.so.0.1.UKlWv9.ltrans14.ltrans.o: in function `path_expand':
/home/[username]/proj/newnewdosemu/bisect/src/base/init/config.c:694: undefined reference to `strlcat'
/usr/bin/ld: /home/[username]/proj/newnewdosemu/bisect/src/base/init/config.c:701: undefined reference to `strlcat'
/usr/bin/ld: /tmp/libdosemu2.so.0.1.UKlWv9.ltrans22.ltrans.o: in function `get_name_from_mcb':
/home/[username]/proj/newnewdosemu/bisect/src/plugin/debugger/mhpdbgc.c:1046: undefined reference to `strlcpy'
/usr/bin/ld: /home/[username]/proj/newnewdosemu/bisect/src/plugin/debugger/mhpdbgc.c:1056: undefined reference to `strlcpy'
/usr/bin/ld: /home/[username]/proj/newnewdosemu/bisect/src/plugin/debugger/mhpdbgc.c:1059: undefined reference to `strlcat'
/usr/bin/ld: /home/[username]/proj/newnewdosemu/bisect/src/plugin/debugger/mhpdbgc.c:1060: undefined reference to `strlcat'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/[username]/proj/newnewdosemu/bisect/src/arch/linux/Makefile.main:95: ../2.0-pre9/bin/libdosemu2.so.0.1] Error 1
make[2]: Leaving directory '/home/[username]/proj/newnewdosemu/bisect/src'
make[1]: *** [/home/[username]/proj/newnewdosemu/bisect/src/arch/linux/Makefile.main:133: dosemu] Error 2
make[1]: Leaving directory '/home/[username]/proj/newnewdosemu/bisect/src'
make: *** [Makefile:42: default] Error 2
```

**Comment by ecm-pushbx** [comment]
bisect$ git bisect bad
e2dad093276437addc142d5165fb0563cf9f8e3c is the first bad commit
commit e2dad093276437addc142d5165fb0563cf9f8e3c
Author: Bart Oldeman <bartoldeman@users.noreply.github.com>
Date:   Mon Nov 24 16:48:41 2025 -0500

    simx86: handle indirect jumps via helper function if possible

    Call Jmp_indirect_helper() to find the next block and jump to it if
    possible. This gives a modest boost in performance but mostly
    makes the fast loop in DoExec() obsolete so cleanups there will
    be possible.

 src/base/emu-i386/simx86/codegen-x86.c | 23 +++++++++++++++++++++++
 src/base/emu-i386/simx86/cpatch.c      | 23 +++++++++++++++++++++++
 src/base/emu-i386/simx86/cpatch.h      |  3 +++
 3 files changed, 49 insertions(+)

**Comment by ecm-pushbx** [comment]
Actually, the bisect bad revision e2dad09 works with `$_cpuemu=(1)` but fails without. 849a11e06 fails regardless.

**Comment by ecm-pushbx** [comment]
I can try to bisect when setting cpuemu to 1 no longer helped, tomorrow.

**Comment by stsp** [comment]
Thanks, its now pretty clear.
The JmpIndirect jumps directly
to the code, bypassing Exec()
loop, thus also bypassing the
TF check.
Please try this:
```
diff --git a/src/base/emu-i386/simx86/cpatch.c b/src/base/emu-i386/simx86/cpatch.c
index 953ea5673..5a5b8ad42 100644
--- a/src/base/emu-i386/simx86/cpatch.c
+++ b/src/base/emu-i386/simx86/cpatch.c
@@ -882,7 +882,7 @@ unsigned char *Jmp_indirect_helper(unsigned int ePC,
     /* excessive e_querynode() seems to not help */
     {
         TNode *G = FindTree(ePC);
-        ret = (G && GoodNode(G)) ? GetExecCodeBuf(G->addr) : tailcode;
+        ret = (G && GoodNode(G) && !exit_pending()) ? GetExecCodeBuf(G->addr) : tailcode;
     }
 #endif
     InCompiledCode++;
```

**Comment by ecm-pushbx** [comment]
Thanks. Without `$_cpuemu=(1)` this succeeds, with `$_cpuemu=(1)` it fails the same way as before.

**Comment by stsp** [comment]
Maybe this helps?
```
--- a/src/base/emu-i386/simx86/codegen-sim.c
+++ b/src/base/emu-i386/simx86/codegen-sim.c
@@ -2638,7 +2638,7 @@ static unsigned int Gen_sim(IGen *IG, unsigned int *pmem_ref)
 #if 1
                                        G &&
 #endif
-                                       GoodNode(G)) {
+                                       GoodNode(G) && !exit_pending()) {
                                IG = (IGen *)G->addr;
                                continue;
                        }
```

**Comment by ecm-pushbx** [comment]
Yes, thank you! With both patches applied it seems to work regardless whether `$_cpuemu=(1)` is used or not.

**Comment by stsp** [comment]
Could you please check d065ef357
instead of anything else?

**Comment by ecm-pushbx** [comment]
Without the two patches you added here or with them still applied?

**Comment by stsp** [comment]
Without anything else.

**Comment by ecm-pushbx** [comment]
Yes, that revision also works, and again regardless `$_cpuemu=(1)`

**Comment by stsp** [comment]
Thanks!
What is this ldos.com stuff?

**Comment by ecm-pushbx** [comment]
> Thanks! What is this ldos.com stuff?

It's [my own DOS kernel](https://pushbx.org/ecm/web/#projects-ldos), largely based on MS-DOS v4.01 with some additions, some originally developed for lRxDOS and lDebug. It supports UMA use (mostly like MS-DOS v5), HMA (like MS-DOS v7), LBA (like v7.00), FAT12/FAT16, up to 256 Sectors per Cluster (like EDR-DOS), splits the DOSDATA and DOSCODE segments (like MS-DOS v5), mostly merges the msbio and msdos kernel parts (like FreeDOS), and can relocate DOSDATA into the UMA or LMA (like DR-DOS v7).

The ldos.com file is the uncompressed, iniload-using single kernel file. It is a dual mode executable, both a kernel mode and an application mode are supported.

The kernel mode iniload-using file can load as RxDOS.3 / lDOS load, FreeDOS / EDR-DOS load, MS-DOS v6 / IBM-DOS load, MS-DOS v7 load, or Multiboot v1/v2 load. So renaming it to kernel.sys or rxdos.com or io.sys or ibmbio.com allows directly booting it in dosemu2, although [I currently use bootable lDebug to boot the kernel](https://pushbx.org/ecm/dokuwiki/blog/pushbx/2025/0304_interlude_current_ldebug_startup_files).

The application mode of ldos.com contains the comloader (command loader), which contains several commands. Most notably the version command, instsect (install boot sector loaders), and patldos (lDOS kernel file configuration utility).

**Comment by stsp** [comment]
Maybe then you'd like to
add its boot support to
dosemu2?

**Comment by ecm-pushbx** [comment]
I'm actually fine with it as is, though you could copy or share the RxDOS.3 / RXN_D load support, the lDOS load is an alias of that one except for the default filename.
