### ISSUE TITLE
ERROR: EMU86: error 96

### ISSUE THREAD

**Issue by haenschen** [dosemu2/dosemu2#2147]
**Describe the bug**
When running my application, dosemu crashes with ERROR: EMU86: error 96.

**To Reproduce**
The application makes use of serial communication but I can also run an office version without it. Crash still occurs.

**Attach program/game binaries or provide an URL**
I can provide private download to the proprietary software if needed.

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/14165828/boot.log)

**A regression?**
Yes, seems like it's a recent regression. I can do a bisect if needed.

**Comment by haenschen** [comment]
Sorry, I attached the wrong boot.log. Reuploaded.

**Comment by stsp** [comment]
It would be interesting to first check
commits 86ffae31 and 9ec078f5
They are easily revertible, so just do:
`git revert 86ffae31`
try the result
`git revert 9ec078f5`
try the result.
If that doesn't reveal anything, then
full bisect would be helpful.

**Comment by haenschen** [comment]
` git revert 86ffae31` unfortunately didn't help

It won't let me do `git revert 9ec078f5` due to a merge conflict in src/base/emu-i386/simx86/interp.c

However, when I try building older versions, make fails due to
`fdpp.c:26:2: error: #error wrong fdpp version
`
I install fdpp from repository, any easy way around this? :)

**Comment by stsp** [comment]
Its actually very strange, because for
me it reverts cleanly.
Note that you should revert them in
exactly that order. I.e. when reverting
9ec078f5, 86ffae31 must be also reverted.

**Comment by haenschen** [comment]
Oops, sorry, you are right. So now I reverted both and checked that I have the correct (old) [interp.c](https://github.com/dosemu2/dosemu2/commit/9ec078f5688fd7af6a1aff6a17af51ee6e91c7b0#diff-2a1758ab199db82215a496a89cc942027c3256875c5e71deff3e95dc43e6dd3d) but it still crashes...

[boot.log](https://github.com/dosemu2/dosemu2/files/14166756/boot.log)

**Comment by stsp** [comment]
There is a script in
`scripts/buildwithfdpp.sh`
that allows you to build the
right version of fdpp during
bisect.
But the much easier solution
is to temporary put freedos's
kernel.sys into C:\ and bisect
without fdpp.
You need to add
`plugin_fdpp off`
into `compiletime-settings.devel`
and you need to run:
`./default-configure -d --disable-fdpp`
before building.

**Comment by andrewbird** [comment]
I'm not sure the buildwithfdpp.sh script is much use now, a lot has changed since it was written.

**Comment by stsp** [comment]
I still tag the apis, so it probably
still works?
Its a bit more simple to just disable
fdpp and bisect dosemu2. But what
to do if you bisect fdpp itself?

**Comment by stsp** [comment]
Or do you mean there is a similar
problem with dj64, so the script
needs updating?
I myself disable dj64 as well for
bisecting, and uninstall comcom64.
Then comcom32 is used during bisecting.
Maybe this all can be somehow
automated?
Like adding another configure
pre-sets for bisecting.

**Comment by stsp** [comment]
But overall its quite sad that all these
new developments only lead to users
complaining on a build process, and
developers complaining on bisect
process. Something should be done
to solve these problems.

**Comment by haenschen** [comment]
So, today I finally got around to try your idea. Building worked right away as you instructed and so I got ecstatic and wanted to find the wrong version but bisecting was exhausting as sometimes builds failed and I had to skip commits.
I started with [2.0pre9](https://github.com/dosemu2/dosemu2/releases/tag/2.0pre9) which didnt work.
[boot_pre9.log](https://github.com/dosemu2/dosemu2/files/14807068/boot_pre9.log)

Naturally I wanted to try earlier versions like [2019end](https://github.com/dosemu2/dosemu2/releases/tag/2019end) and it did work.
So I did a bisect.

```
git bisect start
git bisect good
git bisect bad 2.0pre9
```

After manually adding  `plugin_fdpp off` everytime i did

```
make realclean
./autogen.sh
./default-configure -d --libexecdir=/usr/libexec --disable-fdpp
make
sudo make install
```

and tried my testcase etc

However, bisect was not successful. Something else must have changed because [2.0pre9](https://github.com/dosemu2/dosemu2/releases/tag/2.0pre9) is now also working. 
[boot_pre9_working.log](https://github.com/dosemu2/dosemu2/files/14807704/boot_pre9_working.log)

Any ideas, any other files changed...?

**Comment by stsp** [comment]
`make -j 9` instead of `make` would
save you some time.
I don't think you need to alter libexecdir
when fdpp is disabled.

So if pre9 is also working, then does
devel work as well?

**Comment by stsp** [comment]
Also you usually don't need `make install`.
You can run dosemu from a build dir.
Quite good for bisecting.

**Comment by stsp** [comment]
Also you can give me an ssh and
I'll bisect.

**Comment by haenschen** [comment]
> So if pre9 is also working, then does devel work as well?

Yes, it does.
Okay, I will prepare ssh.

**Comment by stsp** [comment]
For what?
Everything works.

**Comment by haenschen** [comment]
Yes, but why does it work now? I'm pretty sure if I do a new fresh installation it will fail again.

**Comment by stsp** [comment]
Then don't do the installation.
Run dosemu from a build dir.
This way you can get both working
and broken to compare.

**Comment by haenschen** [comment]
Okay, I redid the entire thing and am pretty sure I found the culprit

```
16dfd79eed9eb7eefae53cd9c9b63735d5af0081 is the first bad commit
commit 16dfd79eed9eb7eefae53cd9c9b63735d5af0081
Author: Bart Oldeman <bartoldeman@users.noreply.github.com>
Date:   Wed Apr 5 21:20:48 2023 -0400

    cpuemu: don't also check TheCPU.sigalrm_pending in CeS_INSTREMU check
    
    Fixes performance regression from #1975 / e056787b
    
    It checked for it but didn't reset which caused performance issues (DOOM
    ran much more slowly). It's better to just let the existing sim/interp logic
    check for it and exit the interpreter loop that way when an async signal
    arrives.
    
    Also set TheCPU.sigalrm_pending = 0 when entering cpuemu to make sure it's
    not stuck there from a previous call and prevent the above situation
    completetely.

 src/base/emu-i386/simx86/cpu-emu.c | 2 ++
 src/base/emu-i386/simx86/interp.c  | 2 +-
 2 files changed, 3 insertions(+), 1 deletion(-)
```

**Comment by stsp** [comment]
But haven't you got things already
working? What was needed to reproduce
the problem?

Please write commit hashes unquoted,
like this: 16dfd79eed9e

**Comment by haenschen** [comment]
To reproduce the problem I just deleted the entire source/git directory, cloned it again and built/installed from devel - then the crash occured again :)

**Comment by stsp** [comment]
OK, if this patch is indeed a culprit,
then it would be very difficult to find
the problem w/o reproducer.
So could you please prepare one?
Tarred up drive_c should do.
You can send me the link privately
by e-mail, if you want.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
I applied a different fix for this one.
Could you please re-check?

**Comment by haenschen** [comment]
Yes, still works
