### ISSUE TITLE
Build error: a label can only be part of a statement and a declaration is not a statement

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#2195]
**Describe the bug**
After a `git pull` dosemu2 fails to build:

```
make[2]: Entering directory '[redacted]proj/newnewdosemu/20230222/src/base/lib/timer'
gcc -c -imacros config.hh -MD -DCFLAGS_STR=" -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wundef -Wno-address-of-packed-member -ggdb3 -fpie -O2   " -I../../../../src/include -I../../../../src/plugin/include -I[redacted]proj/newnewdosemu/20230222/src/base/bios/x86 -I[redacted]proj/newnewdosemu/20230222/src/include -I[redacted]proj/newnewdosemu/20230222/src/base/lib  -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wundef -Wno-address-of-packed-member -ggdb3 -fpie -O2    -o evtimer_fd.o evtimer_fd.c
evtimer_fd.c: In function â€˜do_callbackâ€™:
evtimer_fd.c:81:5: error: a label can only be part of a statement and a declaration is not a statement
   81 |     int rc = read(t->fd, &ticks, sizeof(ticks));
      |     ^~~
make[2]: *** [[redacted]proj/newnewdosemu/20230222/src/Makefile.common.post:82: evtimer_fd.o] Error 1
make[2]: Leaving directory '[redacted]proj/newnewdosemu/20230222/src/base/lib/timer'
make[1]: *** [[redacted]proj/newnewdosemu/20230222/src/arch/linux/Makefile.main:118: base/lib/timer] Error 2
make[1]: Leaving directory '[redacted]proj/newnewdosemu/20230222/src'
make: *** [Makefile:30: default] Error 2
dosemu$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

dosemu$
```
**To Reproduce**
1. Check out 3d8e731a6
2. Run `./default-configure`
3. Run `make`

**Attach the log**
Build failure not run time error.

**A regression?**
Yes.

**dosemu2 origins**
Pulled from git, configured using `./default-configure --prefix=$HOME/local.new --with-fdtarball=dosemu-freedos-1.0-bin.tgz --sysconfdir=$HOME/local.new/etc --disable-fdpp --mandir=$HOME/local.new/share/man --datarootdir=$HOME/local.new/share`

**Additional info**

Likely introduced in https://github.com/dosemu2/dosemu2/commit/edf631232b23758f7363a30df27ad702ab2d8095

Known good in https://github.com/dosemu2/dosemu2/commit/184bce73c0ce554f79eefc50071c4783a92dce8f

Seems to be fixed using this patch:

```
diff --git a/src/base/lib/timer/evtimer_fd.c b/src/base/lib/timer/evtimer_fd.c
index 55e5e3404..528a1cbfa 100644
--- a/src/base/lib/timer/evtimer_fd.c
+++ b/src/base/lib/timer/evtimer_fd.c
@@ -77,8 +77,9 @@ static void do_callback(struct evtimer *t)
 {
     uint64_t ticks;
 #ifdef HAVE_TIMERFD_CREATE
+    int rc;
 again:
-    int rc = read(t->fd, &ticks, sizeof(ticks));
+    rc = read(t->fd, &ticks, sizeof(ticks));
     if (rc == -1) {
         if (errno == EAGAIN)  // other thread modified timer
             goto again;
```

**Comment by stsp** [comment]
Interesting.
No build system failed on that, and
the commit that did this, is a month
old...
But thanks.
